### ISSUE TITLE
Use QuartoNotebookRunner instead of IJulia?

### ISSUE THREAD

**Issue by devmotion** [TuringLang/turing-test-website#6]
I think it would be more convenient for developers and contributors if we could avoid the Python dependency introduced by IJulia. As mentioned in https://github.com/TuringLang/TuringTutorials/issues/435#issue-2163134003, I'd suggest using QuartoNotebookRunner which is already officially supported by Quarto in the latest pre-releases (and you can use it also with the stable Quarto releases by manually going from qmd to ipynb with QuartoNotebookRunner and then with quarto from ipynb to html (or whatever output format is desired)).

**Comment by shravanngoswamii** [comment]
I added QuartoNoteBookRunner and the following issues occurred:
1. I have to activate each `.qmd` file using `Pkg.activate(".")` to run its code blocks (I do not know why it's happening or how to avoid it) and without activating, it throws these errors: [https://github.com/shravanngoswamii/turing-test-website/actions/runs/8992506576/job/24702430093#step:8:69](https://github.com/shravanngoswamii/turing-test-website/actions/runs/8992506576/job/24702430093#step:8:69 ), this was not happening when QuartoNoteBookRunner was not in use.
2. I do not understand why but the output of this example is quite different when using QuartoNoteBookRunner. I still did not merge the changes so you can see the comparison between both:
> This Example without QuartoNoteBookRunner: [https://turinglang.org/turing-test-website/docs/using-turing/getting-started.html#example](https://turinglang.org/turing-test-website/docs/using-turing/getting-started.html#example)
> This Example with QuartoNoteBookRunner: [https://shravanngoswamii.github.io/turing-test-website/docs/using-turing/getting-started.html#example](https://shravanngoswamii.github.io/turing-test-website/docs/using-turing/getting-started.html#example)

Screenshot:
| Without QuartoNoteBookRunner | With QuartoNoteBookRunner|
|--------|--------|
| ![Screenshot 2024-05-08 041551](https://github.com/TuringLang/turing-test-website/assets/123811742/7fce5a60-17eb-454b-a7ab-a274eb6cb31f) | ![Screenshot 2024-05-08 041428](https://github.com/TuringLang/turing-test-website/assets/123811742/18f16d02-fea9-4383-9f22-8d8383e35c40) | 

My forked repo is using QuartoNoteBookRunner now: [https://github.com/shravanngoswamii/turing-test-website](https://github.com/shravanngoswamii/turing-test-website)

**Comment by shravanngoswamii** [comment]
I guess each `.qmd` needs to be activated: https://github.com/quarto-dev/quarto-cli/issues/1483

**Comment by shravanngoswamii** [comment]
> Generally, IMO we shouldn't perform Pkg operations such as https://github.com/shravanngoswamii/turing-test-website/blob/a36ef5466bf5418593810deed954d366b8d5f6ec/docs/using-turing/getting-started.qmd#L15-L25 in the notebooks. It would be better to keep Project/Manifest files next to the notebooks with the desired environment. As in IJulia the project environments should be picked up automatically since both IJulia and QuartoNotebookRunner use the julia commandline option `--project=@.` by default when executing the Julia code: [PumasAI/QuartoNotebookRunner.jl#73](https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/73)

I do not seem to understand, I am getting errors if I do not perform the Pkg operation in notebooks or else do I have to maintain Project/Manifest file for each notebook individually?



> The example has progress logging enabled, so the output from QuartoNotebookRunner is what you would get also e.g. in a Github action. TerminalLoggers (the default frontend AbstractMCMC sets up if users did not define anything else) has the same problem on IJulia/Jupyter: [JuliaLogging/TerminalLoggers.jl#25](https://github.com/JuliaLogging/TerminalLoggers.jl/issues/25) However, as a workaround for IJulia AbstractMCMC switches to the (deprecated) ConsoleProgressMonitor: https://github.com/TuringLang/AbstractMCMC.jl/blob/2a77f53114c4b3c5a11a3759e39233dab9e16f9a/src/logging.jl#L40-L47

Is fine to keep that progress log on the website or do we have to remove it?

**Comment by shravanngoswamii** [comment]
> It would be better to keep Project/Manifest files next to the notebooks with the desired environment.

I removed all Pkg operations from notebooks and activated a project in the root directory so now Project/Manifest files are there and in Github action, first it installs all dependencies using `Pkg.instantiate()` and then performs `quarto render` and it's working fine!! let me know if there is any issue and also please just look over the [Github actions](https://github.com/TuringLang/turing-test-website/blob/42dfb40c42a53baeb77c76a3106f70f4541c3cd1/.github/workflows/publish.yml) and let me know if anything is wrong or can be done in better way!!

I also wanted one suggestion, should we use Quarto's `freeze` feature or not, it can fasten the workflows by not always running the code!!

> The example has progress logging enabled, so the output from QuartoNotebookRunner is what you would get also e.g. in a Github action. TerminalLoggers (the default frontend AbstractMCMC sets up if users did not define anything else) has the same problem on IJulia/Jupyter: [JuliaLogging/TerminalLoggers.jl#25](https://github.com/JuliaLogging/TerminalLoggers.jl/issues/25) However, as a workaround for IJulia AbstractMCMC switches to the (deprecated) ConsoleProgressMonitor: https://github.com/TuringLang/AbstractMCMC.jl/blob/2a77f53114c4b3c5a11a3759e39233dab9e16f9a/src/logging.jl#L40-L47

If that progress log is not an issue then I can continue working on other things and if we have to remove it then I will require some help as I am not quite familiar with these!!

**Comment by devmotion** [comment]
> activated a project in the root directory so now Project/Manifest files

For all the tutorials we should just copy the Project.toml + Manifest.toml files from TuringTutorials (if this content is supposed to be moved here). A shared environment in the root is most likely not what we want for most quarto documents - adding dependencies for all documents in one big shared environment makes the environment unnecessarily big and thereby slow to compile for most documents; moreover, large environments tend to lead to version conflicts/dependency downgrades.

> If that progress log is not an issue then I can continue working on other things and if we have to remove it then I will require some help as I am not quite familiar with these!!

The easiest solution is probably to disable progress logging by adding `progress = false` to the `sample` calls.

**Comment by shravanngoswamii** [comment]
> For all the tutorials we should just copy the Project.toml + Manifest.toml files from TuringTutorials

Done, added individual Project.toml and Manifest.toml and also added each notebook in new folders. just look over the current GitHub actions workflow, if it's fine then we can close this issue: [publish.yml](https://github.com/TuringLang/turing-test-website/blob/main/.github/workflows/publish.yml)



> The easiest solution is probably to disable progress logging by adding `progress = false` to the `sample` calls.

I also did this, now progress is not showing but the step size which was showing before progress is still showing:
![Screenshot 2024-05-10 134025](https://github.com/TuringLang/turing-test-website/assets/123811742/1c923a36-1c7e-47b1-8fcf-77e25461dc70)

**Comment by shravanngoswamii** [comment]
@devmotion After I added the individual project.toml and manifest.toml for each notebook, the previous (first 2 notebooks ran fine in github actions but today I added new notebook and added project/manifest for it too in same way but its failing to run with instantiation errors.
Do I have to instantiate each notebook individually every time? and if that's the case then why it was running successfully before!!
here is the failed actions report: https://github.com/shravanngoswamii/turing-test-website/actions/runs/9049662120/job/24864033069

I added a make.jl for individually instantiating every notebook directory but I guess it's not an ideal solution!!
